nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.0.cjs
defaultSemverRangePrefix: ""


npmRegistries:
  "https://packages.aliyun.com/66e2dd9f79b7fe080f32665b/npm/npm-registry/":
    npmAuthToken: 3e6ad778-797d-43fb-a03a-bafb54d23665
    npmAlwaysAuth: true
npmRegistryServer: "https://packages.aliyun.com/66e2dd9f79b7fe080f32665b/npm/npm-registry/"
